api:
  addr: 127.0.0.1:8081
  token: agent-token
application:
  debug: true
  # trace_endpoint: http://localhost:4318/v1/traces
  service_name: hgraber-next-agentfs-local
  use_unsafe_closer: false
fs_base:
  export_path: ./.hidden/export
  file_path: ./.hidden/filedata
  enable_deduplication: true
  export_limit_on_folder: 50
sqlite:
  file_path: db.sqlite
zip_scanner:
  master_addr: http://localhost:8080
  master_token: local-next
