// Code generated by ogen, DO NOT EDIT.

package server

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleHeaderAuth handles headerAuth security.
	// Авторизация через заголовок.
	HandleHeaderAuth(ctx context.Context, operationName string, t HeaderAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityHeaderAuth(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t HeaderAuth
	const parameterName = "X-HG-Agent-Token"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	rctx, err := s.sec.HandleHeaderAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// HeaderAuth provides headerAuth security value.
	// Авторизация через заголовок.
	HeaderAuth(ctx context.Context, operationName string) (HeaderAuth, error)
}

func (s *Client) securityHeaderAuth(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.HeaderAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"HeaderAuth\"")
	}
	req.Header.Set("X-HG-Agent-Token", t.APIKey)
	return nil
}
