// Code generated by ogen, DO NOT EDIT.
package agentAPI

type APICoreStatusGetRes interface {
	aPICoreStatusGetRes()
}

type APIExportArchivePostRes interface {
	aPIExportArchivePostRes()
}

type APIFsCreatePostRes interface {
	aPIFsCreatePostRes()
}

type APIFsDeletePostRes interface {
	aPIFsDeletePostRes()
}

type APIFsGetGetRes interface {
	aPIFsGetGetRes()
}

type APIFsIdsGetRes interface {
	aPIFsIdsGetRes()
}

type APIParsingBookCheckPostRes interface {
	aPIParsingBookCheckPostRes()
}

type APIParsingBookMultiPostRes interface {
	aPIParsingBookMultiPostRes()
}

type APIParsingBookPostRes interface {
	aPIParsingBookPostRes()
}

type APIParsingPageCheckPostRes interface {
	aPIParsingPageCheckPostRes()
}

type APIParsingPagePostRes interface {
	aPIParsingPagePostRes()
}
