// Code generated by ogen, DO NOT EDIT.

package agentAPI

import (
	"bytes"
	"net/http"

	"github.com/go-faster/jx"

	ht "github.com/ogen-go/ogen/http"
)

func encodeAPIExportArchivePostRequest(
	req APIExportArchivePostReq,
	r *http.Request,
) error {
	const contentType = "application/octet-stream"
	body := req
	ht.SetBody(r, body, contentType)
	return nil
}

func encodeAPIFsCreatePostRequest(
	req APIFsCreatePostReq,
	r *http.Request,
) error {
	const contentType = "application/octet-stream"
	body := req
	ht.SetBody(r, body, contentType)
	return nil
}

func encodeAPIFsDeletePostRequest(
	req *APIFsDeletePostReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeAPIParsingBookCheckPostRequest(
	req *APIParsingBookCheckPostReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeAPIParsingBookMultiPostRequest(
	req *APIParsingBookMultiPostReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeAPIParsingBookPostRequest(
	req *APIParsingBookPostReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeAPIParsingPageCheckPostRequest(
	req *APIParsingPageCheckPostReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeAPIParsingPagePostRequest(
	req *APIParsingPagePostReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}
