// Code generated by ogen, DO NOT EDIT.
package serverAPI

type APIAgentDeletePostRes interface {
	aPIAgentDeletePostRes()
}

type APIAgentListPostRes interface {
	aPIAgentListPostRes()
}

type APIAgentNewPostRes interface {
	aPIAgentNewPostRes()
}

type APIAgentTaskExportPostRes interface {
	aPIAgentTaskExportPostRes()
}

type APIBookArchiveIDGetRes interface {
	aPIBookArchiveIDGetRes()
}

type APIBookDeletePostRes interface {
	aPIBookDeletePostRes()
}

type APIBookDetailsPostRes interface {
	aPIBookDetailsPostRes()
}

type APIBookListPostRes interface {
	aPIBookListPostRes()
}

type APIBookRawPostRes interface {
	aPIBookRawPostRes()
}

type APIBookVerifyPostRes interface {
	aPIBookVerifyPostRes()
}

type APIFileIDGetRes interface {
	aPIFileIDGetRes()
}

type APIPageBodyPostRes interface {
	aPIPageBodyPostRes()
}

type APIParsingBookExistsPostRes interface {
	aPIParsingBookExistsPostRes()
}

type APIParsingPageExistsPostRes interface {
	aPIParsingPageExistsPostRes()
}

type APISystemDeduplicateArchivePostRes interface {
	aPISystemDeduplicateArchivePostRes()
}

type APISystemHandlePostRes interface {
	aPISystemHandlePostRes()
}

type APISystemImportArchivePostRes interface {
	aPISystemImportArchivePostRes()
}

type APISystemInfoGetRes interface {
	aPISystemInfoGetRes()
}

type APISystemRPCDeduplicateFilesPostRes interface {
	aPISystemRPCDeduplicateFilesPostRes()
}

type APISystemRPCRemoveDetachedFilesPostRes interface {
	aPISystemRPCRemoveDetachedFilesPostRes()
}

type APISystemRPCRemoveMismatchFilesPostRes interface {
	aPISystemRPCRemoveMismatchFilesPostRes()
}

type APISystemWorkerConfigPostRes interface {
	aPISystemWorkerConfigPostRes()
}

type APIUserLoginPostRes interface {
	aPIUserLoginPostRes()
}
