// Code generated by ogen, DO NOT EDIT.

package serverAPI

import (
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type APIAgentDeletePostBadRequest ErrorResponse

func (*APIAgentDeletePostBadRequest) aPIAgentDeletePostRes() {}

type APIAgentDeletePostForbidden ErrorResponse

func (*APIAgentDeletePostForbidden) aPIAgentDeletePostRes() {}

type APIAgentDeletePostInternalServerError ErrorResponse

func (*APIAgentDeletePostInternalServerError) aPIAgentDeletePostRes() {}

// APIAgentDeletePostNoContent is response for APIAgentDeletePost operation.
type APIAgentDeletePostNoContent struct{}

func (*APIAgentDeletePostNoContent) aPIAgentDeletePostRes() {}

type APIAgentDeletePostNotFound ErrorResponse

func (*APIAgentDeletePostNotFound) aPIAgentDeletePostRes() {}

type APIAgentDeletePostReq struct {
	// ID агента.
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APIAgentDeletePostReq) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APIAgentDeletePostReq) SetID(val uuid.UUID) {
	s.ID = val
}

type APIAgentDeletePostUnauthorized ErrorResponse

func (*APIAgentDeletePostUnauthorized) aPIAgentDeletePostRes() {}

type APIAgentListPostBadRequest ErrorResponse

func (*APIAgentListPostBadRequest) aPIAgentListPostRes() {}

type APIAgentListPostForbidden ErrorResponse

func (*APIAgentListPostForbidden) aPIAgentListPostRes() {}

type APIAgentListPostInternalServerError ErrorResponse

func (*APIAgentListPostInternalServerError) aPIAgentListPostRes() {}

type APIAgentListPostOKApplicationJSON []APIAgentListPostOKItem

func (*APIAgentListPostOKApplicationJSON) aPIAgentListPostRes() {}

type APIAgentListPostOKItem struct {
	// Статус агента.
	Status OptAPIAgentListPostOKItemStatus `json:"status"`
	// ID агента.
	ID uuid.UUID `json:"id"`
	// Название агента.
	Name string `json:"name"`
	// Адрес агента.
	Addr url.URL `json:"addr"`
	// Может ли агент обрабатывать ссылки внешних систем.
	CanParse bool `json:"can_parse"`
	// Может ли агент обрабатывать множественные ссылки
	// внешних систем.
	CanParseMulti bool `json:"can_parse_multi"`
	// Может ли агент экспортировать данные из системы.
	CanExport bool `json:"can_export"`
	// Приоритет при выборе агентов.
	Priority int `json:"priority"`
	// Время создания агента.
	CreateAt time.Time `json:"create_at"`
}

// GetStatus returns the value of Status.
func (s *APIAgentListPostOKItem) GetStatus() OptAPIAgentListPostOKItemStatus {
	return s.Status
}

// GetID returns the value of ID.
func (s *APIAgentListPostOKItem) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *APIAgentListPostOKItem) GetName() string {
	return s.Name
}

// GetAddr returns the value of Addr.
func (s *APIAgentListPostOKItem) GetAddr() url.URL {
	return s.Addr
}

// GetCanParse returns the value of CanParse.
func (s *APIAgentListPostOKItem) GetCanParse() bool {
	return s.CanParse
}

// GetCanParseMulti returns the value of CanParseMulti.
func (s *APIAgentListPostOKItem) GetCanParseMulti() bool {
	return s.CanParseMulti
}

// GetCanExport returns the value of CanExport.
func (s *APIAgentListPostOKItem) GetCanExport() bool {
	return s.CanExport
}

// GetPriority returns the value of Priority.
func (s *APIAgentListPostOKItem) GetPriority() int {
	return s.Priority
}

// GetCreateAt returns the value of CreateAt.
func (s *APIAgentListPostOKItem) GetCreateAt() time.Time {
	return s.CreateAt
}

// SetStatus sets the value of Status.
func (s *APIAgentListPostOKItem) SetStatus(val OptAPIAgentListPostOKItemStatus) {
	s.Status = val
}

// SetID sets the value of ID.
func (s *APIAgentListPostOKItem) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *APIAgentListPostOKItem) SetName(val string) {
	s.Name = val
}

// SetAddr sets the value of Addr.
func (s *APIAgentListPostOKItem) SetAddr(val url.URL) {
	s.Addr = val
}

// SetCanParse sets the value of CanParse.
func (s *APIAgentListPostOKItem) SetCanParse(val bool) {
	s.CanParse = val
}

// SetCanParseMulti sets the value of CanParseMulti.
func (s *APIAgentListPostOKItem) SetCanParseMulti(val bool) {
	s.CanParseMulti = val
}

// SetCanExport sets the value of CanExport.
func (s *APIAgentListPostOKItem) SetCanExport(val bool) {
	s.CanExport = val
}

// SetPriority sets the value of Priority.
func (s *APIAgentListPostOKItem) SetPriority(val int) {
	s.Priority = val
}

// SetCreateAt sets the value of CreateAt.
func (s *APIAgentListPostOKItem) SetCreateAt(val time.Time) {
	s.CreateAt = val
}

// Статус агента.
type APIAgentListPostOKItemStatus struct {
	// Время запуска агента.
	StartAt OptDateTime `json:"start_at"`
	// Ошибка которая возникла при получении статуса.
	CheckStatusError OptString `json:"check_status_error"`
	// Текущее состояние агента.
	Status APIAgentListPostOKItemStatusStatus `json:"status"`
	// Список проблем.
	Problems []APIAgentListPostOKItemStatusProblemsItem `json:"problems"`
}

// GetStartAt returns the value of StartAt.
func (s *APIAgentListPostOKItemStatus) GetStartAt() OptDateTime {
	return s.StartAt
}

// GetCheckStatusError returns the value of CheckStatusError.
func (s *APIAgentListPostOKItemStatus) GetCheckStatusError() OptString {
	return s.CheckStatusError
}

// GetStatus returns the value of Status.
func (s *APIAgentListPostOKItemStatus) GetStatus() APIAgentListPostOKItemStatusStatus {
	return s.Status
}

// GetProblems returns the value of Problems.
func (s *APIAgentListPostOKItemStatus) GetProblems() []APIAgentListPostOKItemStatusProblemsItem {
	return s.Problems
}

// SetStartAt sets the value of StartAt.
func (s *APIAgentListPostOKItemStatus) SetStartAt(val OptDateTime) {
	s.StartAt = val
}

// SetCheckStatusError sets the value of CheckStatusError.
func (s *APIAgentListPostOKItemStatus) SetCheckStatusError(val OptString) {
	s.CheckStatusError = val
}

// SetStatus sets the value of Status.
func (s *APIAgentListPostOKItemStatus) SetStatus(val APIAgentListPostOKItemStatusStatus) {
	s.Status = val
}

// SetProblems sets the value of Problems.
func (s *APIAgentListPostOKItemStatus) SetProblems(val []APIAgentListPostOKItemStatusProblemsItem) {
	s.Problems = val
}

type APIAgentListPostOKItemStatusProblemsItem struct {
	// Тип проблемы.
	Type APIAgentListPostOKItemStatusProblemsItemType `json:"type"`
	// Описание проблемы.
	Details string `json:"details"`
}

// GetType returns the value of Type.
func (s *APIAgentListPostOKItemStatusProblemsItem) GetType() APIAgentListPostOKItemStatusProblemsItemType {
	return s.Type
}

// GetDetails returns the value of Details.
func (s *APIAgentListPostOKItemStatusProblemsItem) GetDetails() string {
	return s.Details
}

// SetType sets the value of Type.
func (s *APIAgentListPostOKItemStatusProblemsItem) SetType(val APIAgentListPostOKItemStatusProblemsItemType) {
	s.Type = val
}

// SetDetails sets the value of Details.
func (s *APIAgentListPostOKItemStatusProblemsItem) SetDetails(val string) {
	s.Details = val
}

// Тип проблемы.
type APIAgentListPostOKItemStatusProblemsItemType string

const (
	APIAgentListPostOKItemStatusProblemsItemTypeInfo    APIAgentListPostOKItemStatusProblemsItemType = "info"
	APIAgentListPostOKItemStatusProblemsItemTypeWarning APIAgentListPostOKItemStatusProblemsItemType = "warning"
	APIAgentListPostOKItemStatusProblemsItemTypeError   APIAgentListPostOKItemStatusProblemsItemType = "error"
)

// AllValues returns all APIAgentListPostOKItemStatusProblemsItemType values.
func (APIAgentListPostOKItemStatusProblemsItemType) AllValues() []APIAgentListPostOKItemStatusProblemsItemType {
	return []APIAgentListPostOKItemStatusProblemsItemType{
		APIAgentListPostOKItemStatusProblemsItemTypeInfo,
		APIAgentListPostOKItemStatusProblemsItemTypeWarning,
		APIAgentListPostOKItemStatusProblemsItemTypeError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIAgentListPostOKItemStatusProblemsItemType) MarshalText() ([]byte, error) {
	switch s {
	case APIAgentListPostOKItemStatusProblemsItemTypeInfo:
		return []byte(s), nil
	case APIAgentListPostOKItemStatusProblemsItemTypeWarning:
		return []byte(s), nil
	case APIAgentListPostOKItemStatusProblemsItemTypeError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIAgentListPostOKItemStatusProblemsItemType) UnmarshalText(data []byte) error {
	switch APIAgentListPostOKItemStatusProblemsItemType(data) {
	case APIAgentListPostOKItemStatusProblemsItemTypeInfo:
		*s = APIAgentListPostOKItemStatusProblemsItemTypeInfo
		return nil
	case APIAgentListPostOKItemStatusProblemsItemTypeWarning:
		*s = APIAgentListPostOKItemStatusProblemsItemTypeWarning
		return nil
	case APIAgentListPostOKItemStatusProblemsItemTypeError:
		*s = APIAgentListPostOKItemStatusProblemsItemTypeError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Текущее состояние агента.
type APIAgentListPostOKItemStatusStatus string

const (
	APIAgentListPostOKItemStatusStatusOk      APIAgentListPostOKItemStatusStatus = "ok"
	APIAgentListPostOKItemStatusStatusWarning APIAgentListPostOKItemStatusStatus = "warning"
	APIAgentListPostOKItemStatusStatusError   APIAgentListPostOKItemStatusStatus = "error"
	APIAgentListPostOKItemStatusStatusOffline APIAgentListPostOKItemStatusStatus = "offline"
	APIAgentListPostOKItemStatusStatusUnknown APIAgentListPostOKItemStatusStatus = "unknown"
)

// AllValues returns all APIAgentListPostOKItemStatusStatus values.
func (APIAgentListPostOKItemStatusStatus) AllValues() []APIAgentListPostOKItemStatusStatus {
	return []APIAgentListPostOKItemStatusStatus{
		APIAgentListPostOKItemStatusStatusOk,
		APIAgentListPostOKItemStatusStatusWarning,
		APIAgentListPostOKItemStatusStatusError,
		APIAgentListPostOKItemStatusStatusOffline,
		APIAgentListPostOKItemStatusStatusUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIAgentListPostOKItemStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case APIAgentListPostOKItemStatusStatusOk:
		return []byte(s), nil
	case APIAgentListPostOKItemStatusStatusWarning:
		return []byte(s), nil
	case APIAgentListPostOKItemStatusStatusError:
		return []byte(s), nil
	case APIAgentListPostOKItemStatusStatusOffline:
		return []byte(s), nil
	case APIAgentListPostOKItemStatusStatusUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIAgentListPostOKItemStatusStatus) UnmarshalText(data []byte) error {
	switch APIAgentListPostOKItemStatusStatus(data) {
	case APIAgentListPostOKItemStatusStatusOk:
		*s = APIAgentListPostOKItemStatusStatusOk
		return nil
	case APIAgentListPostOKItemStatusStatusWarning:
		*s = APIAgentListPostOKItemStatusStatusWarning
		return nil
	case APIAgentListPostOKItemStatusStatusError:
		*s = APIAgentListPostOKItemStatusStatusError
		return nil
	case APIAgentListPostOKItemStatusStatusOffline:
		*s = APIAgentListPostOKItemStatusStatusOffline
		return nil
	case APIAgentListPostOKItemStatusStatusUnknown:
		*s = APIAgentListPostOKItemStatusStatusUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type APIAgentListPostReq struct {
	// Может ли агент обрабатывать ссылки внешних систем.
	CanParse OptBool `json:"can_parse"`
	// Может ли агент экспортировать данные из системы.
	CanExport OptBool `json:"can_export"`
	// Может ли агент обрабатывать множественные ссылки
	// внешних систем.
	CanParseMulti OptBool `json:"can_parse_multi"`
	// Может ли агент экспортировать данные из системы.
	IncludeStatus OptBool `json:"include_status"`
}

// GetCanParse returns the value of CanParse.
func (s *APIAgentListPostReq) GetCanParse() OptBool {
	return s.CanParse
}

// GetCanExport returns the value of CanExport.
func (s *APIAgentListPostReq) GetCanExport() OptBool {
	return s.CanExport
}

// GetCanParseMulti returns the value of CanParseMulti.
func (s *APIAgentListPostReq) GetCanParseMulti() OptBool {
	return s.CanParseMulti
}

// GetIncludeStatus returns the value of IncludeStatus.
func (s *APIAgentListPostReq) GetIncludeStatus() OptBool {
	return s.IncludeStatus
}

// SetCanParse sets the value of CanParse.
func (s *APIAgentListPostReq) SetCanParse(val OptBool) {
	s.CanParse = val
}

// SetCanExport sets the value of CanExport.
func (s *APIAgentListPostReq) SetCanExport(val OptBool) {
	s.CanExport = val
}

// SetCanParseMulti sets the value of CanParseMulti.
func (s *APIAgentListPostReq) SetCanParseMulti(val OptBool) {
	s.CanParseMulti = val
}

// SetIncludeStatus sets the value of IncludeStatus.
func (s *APIAgentListPostReq) SetIncludeStatus(val OptBool) {
	s.IncludeStatus = val
}

type APIAgentListPostUnauthorized ErrorResponse

func (*APIAgentListPostUnauthorized) aPIAgentListPostRes() {}

type APIAgentNewPostBadRequest ErrorResponse

func (*APIAgentNewPostBadRequest) aPIAgentNewPostRes() {}

type APIAgentNewPostForbidden ErrorResponse

func (*APIAgentNewPostForbidden) aPIAgentNewPostRes() {}

type APIAgentNewPostInternalServerError ErrorResponse

func (*APIAgentNewPostInternalServerError) aPIAgentNewPostRes() {}

// APIAgentNewPostNoContent is response for APIAgentNewPost operation.
type APIAgentNewPostNoContent struct{}

func (*APIAgentNewPostNoContent) aPIAgentNewPostRes() {}

type APIAgentNewPostReq struct {
	// Название агента.
	Name string `json:"name"`
	// Адрес агента.
	Addr url.URL `json:"addr"`
	// Токен доступа к агенту.
	Token string `json:"token"`
	// Может ли агент обрабатывать ссылки внешних систем.
	CanParse OptBool `json:"can_parse"`
	// Может ли агент обрабатывать множественные ссылки
	// внешних систем.
	CanParseMulti OptBool `json:"can_parse_multi"`
	// Может ли агент экспортировать данные из системы.
	CanExport OptBool `json:"can_export"`
	// Приоритет при выборе агентов.
	Priority OptInt `json:"priority"`
}

// GetName returns the value of Name.
func (s *APIAgentNewPostReq) GetName() string {
	return s.Name
}

// GetAddr returns the value of Addr.
func (s *APIAgentNewPostReq) GetAddr() url.URL {
	return s.Addr
}

// GetToken returns the value of Token.
func (s *APIAgentNewPostReq) GetToken() string {
	return s.Token
}

// GetCanParse returns the value of CanParse.
func (s *APIAgentNewPostReq) GetCanParse() OptBool {
	return s.CanParse
}

// GetCanParseMulti returns the value of CanParseMulti.
func (s *APIAgentNewPostReq) GetCanParseMulti() OptBool {
	return s.CanParseMulti
}

// GetCanExport returns the value of CanExport.
func (s *APIAgentNewPostReq) GetCanExport() OptBool {
	return s.CanExport
}

// GetPriority returns the value of Priority.
func (s *APIAgentNewPostReq) GetPriority() OptInt {
	return s.Priority
}

// SetName sets the value of Name.
func (s *APIAgentNewPostReq) SetName(val string) {
	s.Name = val
}

// SetAddr sets the value of Addr.
func (s *APIAgentNewPostReq) SetAddr(val url.URL) {
	s.Addr = val
}

// SetToken sets the value of Token.
func (s *APIAgentNewPostReq) SetToken(val string) {
	s.Token = val
}

// SetCanParse sets the value of CanParse.
func (s *APIAgentNewPostReq) SetCanParse(val OptBool) {
	s.CanParse = val
}

// SetCanParseMulti sets the value of CanParseMulti.
func (s *APIAgentNewPostReq) SetCanParseMulti(val OptBool) {
	s.CanParseMulti = val
}

// SetCanExport sets the value of CanExport.
func (s *APIAgentNewPostReq) SetCanExport(val OptBool) {
	s.CanExport = val
}

// SetPriority sets the value of Priority.
func (s *APIAgentNewPostReq) SetPriority(val OptInt) {
	s.Priority = val
}

type APIAgentNewPostUnauthorized ErrorResponse

func (*APIAgentNewPostUnauthorized) aPIAgentNewPostRes() {}

type APIAgentTaskExportPostBadRequest ErrorResponse

func (*APIAgentTaskExportPostBadRequest) aPIAgentTaskExportPostRes() {}

type APIAgentTaskExportPostForbidden ErrorResponse

func (*APIAgentTaskExportPostForbidden) aPIAgentTaskExportPostRes() {}

type APIAgentTaskExportPostInternalServerError ErrorResponse

func (*APIAgentTaskExportPostInternalServerError) aPIAgentTaskExportPostRes() {}

// APIAgentTaskExportPostNoContent is response for APIAgentTaskExportPost operation.
type APIAgentTaskExportPostNoContent struct{}

func (*APIAgentTaskExportPostNoContent) aPIAgentTaskExportPostRes() {}

type APIAgentTaskExportPostReq struct {
	// Время создание книги от.
	From time.Time `json:"from"`
	// Время создание книги до.
	To time.Time `json:"to"`
	// ID агента.
	Exporter uuid.UUID `json:"exporter"`
}

// GetFrom returns the value of From.
func (s *APIAgentTaskExportPostReq) GetFrom() time.Time {
	return s.From
}

// GetTo returns the value of To.
func (s *APIAgentTaskExportPostReq) GetTo() time.Time {
	return s.To
}

// GetExporter returns the value of Exporter.
func (s *APIAgentTaskExportPostReq) GetExporter() uuid.UUID {
	return s.Exporter
}

// SetFrom sets the value of From.
func (s *APIAgentTaskExportPostReq) SetFrom(val time.Time) {
	s.From = val
}

// SetTo sets the value of To.
func (s *APIAgentTaskExportPostReq) SetTo(val time.Time) {
	s.To = val
}

// SetExporter sets the value of Exporter.
func (s *APIAgentTaskExportPostReq) SetExporter(val uuid.UUID) {
	s.Exporter = val
}

type APIAgentTaskExportPostUnauthorized ErrorResponse

func (*APIAgentTaskExportPostUnauthorized) aPIAgentTaskExportPostRes() {}

type APIBookArchiveIDGetBadRequest ErrorResponse

func (*APIBookArchiveIDGetBadRequest) aPIBookArchiveIDGetRes() {}

type APIBookArchiveIDGetForbidden ErrorResponse

func (*APIBookArchiveIDGetForbidden) aPIBookArchiveIDGetRes() {}

type APIBookArchiveIDGetInternalServerError ErrorResponse

func (*APIBookArchiveIDGetInternalServerError) aPIBookArchiveIDGetRes() {}

type APIBookArchiveIDGetNotFound ErrorResponse

func (*APIBookArchiveIDGetNotFound) aPIBookArchiveIDGetRes() {}

type APIBookArchiveIDGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIBookArchiveIDGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*APIBookArchiveIDGetOK) aPIBookArchiveIDGetRes() {}

type APIBookArchiveIDGetUnauthorized ErrorResponse

func (*APIBookArchiveIDGetUnauthorized) aPIBookArchiveIDGetRes() {}

type APIBookDeletePostBadRequest ErrorResponse

func (*APIBookDeletePostBadRequest) aPIBookDeletePostRes() {}

type APIBookDeletePostForbidden ErrorResponse

func (*APIBookDeletePostForbidden) aPIBookDeletePostRes() {}

type APIBookDeletePostInternalServerError ErrorResponse

func (*APIBookDeletePostInternalServerError) aPIBookDeletePostRes() {}

// APIBookDeletePostNoContent is response for APIBookDeletePost operation.
type APIBookDeletePostNoContent struct{}

func (*APIBookDeletePostNoContent) aPIBookDeletePostRes() {}

type APIBookDeletePostNotFound ErrorResponse

func (*APIBookDeletePostNotFound) aPIBookDeletePostRes() {}

type APIBookDeletePostReq struct {
	// ID книги.
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APIBookDeletePostReq) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APIBookDeletePostReq) SetID(val uuid.UUID) {
	s.ID = val
}

type APIBookDeletePostUnauthorized ErrorResponse

func (*APIBookDeletePostUnauthorized) aPIBookDeletePostRes() {}

type APIBookDetailsPostBadRequest ErrorResponse

func (*APIBookDetailsPostBadRequest) aPIBookDetailsPostRes() {}

type APIBookDetailsPostForbidden ErrorResponse

func (*APIBookDetailsPostForbidden) aPIBookDetailsPostRes() {}

type APIBookDetailsPostInternalServerError ErrorResponse

func (*APIBookDetailsPostInternalServerError) aPIBookDetailsPostRes() {}

type APIBookDetailsPostNotFound ErrorResponse

func (*APIBookDetailsPostNotFound) aPIBookDetailsPostRes() {}

type APIBookDetailsPostReq struct {
	// ID книги.
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APIBookDetailsPostReq) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APIBookDetailsPostReq) SetID(val uuid.UUID) {
	s.ID = val
}

type APIBookDetailsPostUnauthorized ErrorResponse

func (*APIBookDetailsPostUnauthorized) aPIBookDetailsPostRes() {}

type APIBookListPostBadRequest ErrorResponse

func (*APIBookListPostBadRequest) aPIBookListPostRes() {}

type APIBookListPostForbidden ErrorResponse

func (*APIBookListPostForbidden) aPIBookListPostRes() {}

type APIBookListPostInternalServerError ErrorResponse

func (*APIBookListPostInternalServerError) aPIBookListPostRes() {}

type APIBookListPostOK struct {
	// Список книг.
	Books []BookShortInfo `json:"books"`
	// Форматированный список страниц.
	Pages []APIBookListPostOKPagesItem `json:"pages"`
}

// GetBooks returns the value of Books.
func (s *APIBookListPostOK) GetBooks() []BookShortInfo {
	return s.Books
}

// GetPages returns the value of Pages.
func (s *APIBookListPostOK) GetPages() []APIBookListPostOKPagesItem {
	return s.Pages
}

// SetBooks sets the value of Books.
func (s *APIBookListPostOK) SetBooks(val []BookShortInfo) {
	s.Books = val
}

// SetPages sets the value of Pages.
func (s *APIBookListPostOK) SetPages(val []APIBookListPostOKPagesItem) {
	s.Pages = val
}

func (*APIBookListPostOK) aPIBookListPostRes() {}

type APIBookListPostOKPagesItem struct {
	// Номер страницы.
	Value int `json:"value"`
	// Это активная страница (по факту запрошенная).
	IsCurrent bool `json:"is_current"`
	// Это разделитель страниц.
	IsSeparator bool `json:"is_separator"`
}

// GetValue returns the value of Value.
func (s *APIBookListPostOKPagesItem) GetValue() int {
	return s.Value
}

// GetIsCurrent returns the value of IsCurrent.
func (s *APIBookListPostOKPagesItem) GetIsCurrent() bool {
	return s.IsCurrent
}

// GetIsSeparator returns the value of IsSeparator.
func (s *APIBookListPostOKPagesItem) GetIsSeparator() bool {
	return s.IsSeparator
}

// SetValue sets the value of Value.
func (s *APIBookListPostOKPagesItem) SetValue(val int) {
	s.Value = val
}

// SetIsCurrent sets the value of IsCurrent.
func (s *APIBookListPostOKPagesItem) SetIsCurrent(val bool) {
	s.IsCurrent = val
}

// SetIsSeparator sets the value of IsSeparator.
func (s *APIBookListPostOKPagesItem) SetIsSeparator(val bool) {
	s.IsSeparator = val
}

type APIBookListPostReq struct {
	// Количество книг на странице.
	Count int `json:"count"`
	// Номер страницы.
	Page OptInt `json:"page"`
	// Статус подтверждения книги.
	VerifyStatus OptAPIBookListPostReqVerifyStatus `json:"verify_status"`
	// Статус удаления книги.
	DeleteStatus OptAPIBookListPostReqDeleteStatus `json:"delete_status"`
	// Фильтр по полям.
	Filter OptAPIBookListPostReqFilter `json:"filter"`
}

// GetCount returns the value of Count.
func (s *APIBookListPostReq) GetCount() int {
	return s.Count
}

// GetPage returns the value of Page.
func (s *APIBookListPostReq) GetPage() OptInt {
	return s.Page
}

// GetVerifyStatus returns the value of VerifyStatus.
func (s *APIBookListPostReq) GetVerifyStatus() OptAPIBookListPostReqVerifyStatus {
	return s.VerifyStatus
}

// GetDeleteStatus returns the value of DeleteStatus.
func (s *APIBookListPostReq) GetDeleteStatus() OptAPIBookListPostReqDeleteStatus {
	return s.DeleteStatus
}

// GetFilter returns the value of Filter.
func (s *APIBookListPostReq) GetFilter() OptAPIBookListPostReqFilter {
	return s.Filter
}

// SetCount sets the value of Count.
func (s *APIBookListPostReq) SetCount(val int) {
	s.Count = val
}

// SetPage sets the value of Page.
func (s *APIBookListPostReq) SetPage(val OptInt) {
	s.Page = val
}

// SetVerifyStatus sets the value of VerifyStatus.
func (s *APIBookListPostReq) SetVerifyStatus(val OptAPIBookListPostReqVerifyStatus) {
	s.VerifyStatus = val
}

// SetDeleteStatus sets the value of DeleteStatus.
func (s *APIBookListPostReq) SetDeleteStatus(val OptAPIBookListPostReqDeleteStatus) {
	s.DeleteStatus = val
}

// SetFilter sets the value of Filter.
func (s *APIBookListPostReq) SetFilter(val OptAPIBookListPostReqFilter) {
	s.Filter = val
}

// Статус удаления книги.
type APIBookListPostReqDeleteStatus string

const (
	APIBookListPostReqDeleteStatusAll    APIBookListPostReqDeleteStatus = "all"
	APIBookListPostReqDeleteStatusOnly   APIBookListPostReqDeleteStatus = "only"
	APIBookListPostReqDeleteStatusExcept APIBookListPostReqDeleteStatus = "except"
)

// AllValues returns all APIBookListPostReqDeleteStatus values.
func (APIBookListPostReqDeleteStatus) AllValues() []APIBookListPostReqDeleteStatus {
	return []APIBookListPostReqDeleteStatus{
		APIBookListPostReqDeleteStatusAll,
		APIBookListPostReqDeleteStatusOnly,
		APIBookListPostReqDeleteStatusExcept,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIBookListPostReqDeleteStatus) MarshalText() ([]byte, error) {
	switch s {
	case APIBookListPostReqDeleteStatusAll:
		return []byte(s), nil
	case APIBookListPostReqDeleteStatusOnly:
		return []byte(s), nil
	case APIBookListPostReqDeleteStatusExcept:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIBookListPostReqDeleteStatus) UnmarshalText(data []byte) error {
	switch APIBookListPostReqDeleteStatus(data) {
	case APIBookListPostReqDeleteStatusAll:
		*s = APIBookListPostReqDeleteStatusAll
		return nil
	case APIBookListPostReqDeleteStatusOnly:
		*s = APIBookListPostReqDeleteStatusOnly
		return nil
	case APIBookListPostReqDeleteStatusExcept:
		*s = APIBookListPostReqDeleteStatusExcept
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Фильтр по полям.
type APIBookListPostReqFilter struct {
	// Фильтр по названию, без учета регистра.
	Name OptString `json:"name"`
}

// GetName returns the value of Name.
func (s *APIBookListPostReqFilter) GetName() OptString {
	return s.Name
}

// SetName sets the value of Name.
func (s *APIBookListPostReqFilter) SetName(val OptString) {
	s.Name = val
}

// Статус подтверждения книги.
type APIBookListPostReqVerifyStatus string

const (
	APIBookListPostReqVerifyStatusAll    APIBookListPostReqVerifyStatus = "all"
	APIBookListPostReqVerifyStatusOnly   APIBookListPostReqVerifyStatus = "only"
	APIBookListPostReqVerifyStatusExcept APIBookListPostReqVerifyStatus = "except"
)

// AllValues returns all APIBookListPostReqVerifyStatus values.
func (APIBookListPostReqVerifyStatus) AllValues() []APIBookListPostReqVerifyStatus {
	return []APIBookListPostReqVerifyStatus{
		APIBookListPostReqVerifyStatusAll,
		APIBookListPostReqVerifyStatusOnly,
		APIBookListPostReqVerifyStatusExcept,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIBookListPostReqVerifyStatus) MarshalText() ([]byte, error) {
	switch s {
	case APIBookListPostReqVerifyStatusAll:
		return []byte(s), nil
	case APIBookListPostReqVerifyStatusOnly:
		return []byte(s), nil
	case APIBookListPostReqVerifyStatusExcept:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIBookListPostReqVerifyStatus) UnmarshalText(data []byte) error {
	switch APIBookListPostReqVerifyStatus(data) {
	case APIBookListPostReqVerifyStatusAll:
		*s = APIBookListPostReqVerifyStatusAll
		return nil
	case APIBookListPostReqVerifyStatusOnly:
		*s = APIBookListPostReqVerifyStatusOnly
		return nil
	case APIBookListPostReqVerifyStatusExcept:
		*s = APIBookListPostReqVerifyStatusExcept
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type APIBookListPostUnauthorized ErrorResponse

func (*APIBookListPostUnauthorized) aPIBookListPostRes() {}

type APIBookRawPostBadRequest ErrorResponse

func (*APIBookRawPostBadRequest) aPIBookRawPostRes() {}

type APIBookRawPostForbidden ErrorResponse

func (*APIBookRawPostForbidden) aPIBookRawPostRes() {}

type APIBookRawPostInternalServerError ErrorResponse

func (*APIBookRawPostInternalServerError) aPIBookRawPostRes() {}

type APIBookRawPostNotFound ErrorResponse

func (*APIBookRawPostNotFound) aPIBookRawPostRes() {}

type APIBookRawPostReq struct {
	// ID книги.
	ID OptUUID `json:"id"`
	// Оригинальный URL книги.
	URL OptURI `json:"url"`
}

// GetID returns the value of ID.
func (s *APIBookRawPostReq) GetID() OptUUID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *APIBookRawPostReq) GetURL() OptURI {
	return s.URL
}

// SetID sets the value of ID.
func (s *APIBookRawPostReq) SetID(val OptUUID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *APIBookRawPostReq) SetURL(val OptURI) {
	s.URL = val
}

type APIBookRawPostUnauthorized ErrorResponse

func (*APIBookRawPostUnauthorized) aPIBookRawPostRes() {}

type APIBookVerifyPostBadRequest ErrorResponse

func (*APIBookVerifyPostBadRequest) aPIBookVerifyPostRes() {}

type APIBookVerifyPostForbidden ErrorResponse

func (*APIBookVerifyPostForbidden) aPIBookVerifyPostRes() {}

type APIBookVerifyPostInternalServerError ErrorResponse

func (*APIBookVerifyPostInternalServerError) aPIBookVerifyPostRes() {}

// APIBookVerifyPostNoContent is response for APIBookVerifyPost operation.
type APIBookVerifyPostNoContent struct{}

func (*APIBookVerifyPostNoContent) aPIBookVerifyPostRes() {}

type APIBookVerifyPostNotFound ErrorResponse

func (*APIBookVerifyPostNotFound) aPIBookVerifyPostRes() {}

type APIBookVerifyPostReq struct {
	// ID книги.
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APIBookVerifyPostReq) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APIBookVerifyPostReq) SetID(val uuid.UUID) {
	s.ID = val
}

type APIBookVerifyPostUnauthorized ErrorResponse

func (*APIBookVerifyPostUnauthorized) aPIBookVerifyPostRes() {}

type APIFileIDGetBadRequest ErrorResponse

func (*APIFileIDGetBadRequest) aPIFileIDGetRes() {}

type APIFileIDGetForbidden ErrorResponse

func (*APIFileIDGetForbidden) aPIFileIDGetRes() {}

type APIFileIDGetInternalServerError ErrorResponse

func (*APIFileIDGetInternalServerError) aPIFileIDGetRes() {}

type APIFileIDGetNotFound ErrorResponse

func (*APIFileIDGetNotFound) aPIFileIDGetRes() {}

type APIFileIDGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIFileIDGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// APIFileIDGetOKHeaders wraps APIFileIDGetOK with response headers.
type APIFileIDGetOKHeaders struct {
	ContentType string
	Response    APIFileIDGetOK
}

// GetContentType returns the value of ContentType.
func (s *APIFileIDGetOKHeaders) GetContentType() string {
	return s.ContentType
}

// GetResponse returns the value of Response.
func (s *APIFileIDGetOKHeaders) GetResponse() APIFileIDGetOK {
	return s.Response
}

// SetContentType sets the value of ContentType.
func (s *APIFileIDGetOKHeaders) SetContentType(val string) {
	s.ContentType = val
}

// SetResponse sets the value of Response.
func (s *APIFileIDGetOKHeaders) SetResponse(val APIFileIDGetOK) {
	s.Response = val
}

func (*APIFileIDGetOKHeaders) aPIFileIDGetRes() {}

type APIFileIDGetUnauthorized ErrorResponse

func (*APIFileIDGetUnauthorized) aPIFileIDGetRes() {}

type APIPageBodyPostBadRequest ErrorResponse

func (*APIPageBodyPostBadRequest) aPIPageBodyPostRes() {}

type APIPageBodyPostForbidden ErrorResponse

func (*APIPageBodyPostForbidden) aPIPageBodyPostRes() {}

type APIPageBodyPostInternalServerError ErrorResponse

func (*APIPageBodyPostInternalServerError) aPIPageBodyPostRes() {}

type APIPageBodyPostNotFound ErrorResponse

func (*APIPageBodyPostNotFound) aPIPageBodyPostRes() {}

type APIPageBodyPostOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APIPageBodyPostOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*APIPageBodyPostOK) aPIPageBodyPostRes() {}

type APIPageBodyPostReq struct {
	// ID книги.
	ID OptUUID `json:"id"`
	// Номер страницы.
	PageNumber OptInt `json:"page_number"`
	// Оригинальный URL страницы.
	URL OptURI `json:"url"`
}

// GetID returns the value of ID.
func (s *APIPageBodyPostReq) GetID() OptUUID {
	return s.ID
}

// GetPageNumber returns the value of PageNumber.
func (s *APIPageBodyPostReq) GetPageNumber() OptInt {
	return s.PageNumber
}

// GetURL returns the value of URL.
func (s *APIPageBodyPostReq) GetURL() OptURI {
	return s.URL
}

// SetID sets the value of ID.
func (s *APIPageBodyPostReq) SetID(val OptUUID) {
	s.ID = val
}

// SetPageNumber sets the value of PageNumber.
func (s *APIPageBodyPostReq) SetPageNumber(val OptInt) {
	s.PageNumber = val
}

// SetURL sets the value of URL.
func (s *APIPageBodyPostReq) SetURL(val OptURI) {
	s.URL = val
}

type APIPageBodyPostUnauthorized ErrorResponse

func (*APIPageBodyPostUnauthorized) aPIPageBodyPostRes() {}

type APIParsingBookExistsPostBadRequest ErrorResponse

func (*APIParsingBookExistsPostBadRequest) aPIParsingBookExistsPostRes() {}

type APIParsingBookExistsPostForbidden ErrorResponse

func (*APIParsingBookExistsPostForbidden) aPIParsingBookExistsPostRes() {}

type APIParsingBookExistsPostInternalServerError ErrorResponse

func (*APIParsingBookExistsPostInternalServerError) aPIParsingBookExistsPostRes() {}

type APIParsingBookExistsPostOK struct {
	// Результат обработки.
	Result []APIParsingBookExistsPostOKResultItem `json:"result"`
}

// GetResult returns the value of Result.
func (s *APIParsingBookExistsPostOK) GetResult() []APIParsingBookExistsPostOKResultItem {
	return s.Result
}

// SetResult sets the value of Result.
func (s *APIParsingBookExistsPostOK) SetResult(val []APIParsingBookExistsPostOKResultItem) {
	s.Result = val
}

func (*APIParsingBookExistsPostOK) aPIParsingBookExistsPostRes() {}

type APIParsingBookExistsPostOKResultItem struct {
	// Ссылка на внешнюю систему.
	URL url.URL `json:"url"`
	// Результат проверки.
	Result APIParsingBookExistsPostOKResultItemResult `json:"result"`
	// Данные об ошибке во время обработки.
	ErrorDetails OptString `json:"error_details"`
	// Список возможных ссылок дубликатов (зеркала внешних
	// систем и т.п.).
	PossibleDuplicates []url.URL `json:"possible_duplicates"`
}

// GetURL returns the value of URL.
func (s *APIParsingBookExistsPostOKResultItem) GetURL() url.URL {
	return s.URL
}

// GetResult returns the value of Result.
func (s *APIParsingBookExistsPostOKResultItem) GetResult() APIParsingBookExistsPostOKResultItemResult {
	return s.Result
}

// GetErrorDetails returns the value of ErrorDetails.
func (s *APIParsingBookExistsPostOKResultItem) GetErrorDetails() OptString {
	return s.ErrorDetails
}

// GetPossibleDuplicates returns the value of PossibleDuplicates.
func (s *APIParsingBookExistsPostOKResultItem) GetPossibleDuplicates() []url.URL {
	return s.PossibleDuplicates
}

// SetURL sets the value of URL.
func (s *APIParsingBookExistsPostOKResultItem) SetURL(val url.URL) {
	s.URL = val
}

// SetResult sets the value of Result.
func (s *APIParsingBookExistsPostOKResultItem) SetResult(val APIParsingBookExistsPostOKResultItemResult) {
	s.Result = val
}

// SetErrorDetails sets the value of ErrorDetails.
func (s *APIParsingBookExistsPostOKResultItem) SetErrorDetails(val OptString) {
	s.ErrorDetails = val
}

// SetPossibleDuplicates sets the value of PossibleDuplicates.
func (s *APIParsingBookExistsPostOKResultItem) SetPossibleDuplicates(val []url.URL) {
	s.PossibleDuplicates = val
}

// Результат проверки.
type APIParsingBookExistsPostOKResultItemResult string

const (
	APIParsingBookExistsPostOKResultItemResultOk          APIParsingBookExistsPostOKResultItemResult = "ok"
	APIParsingBookExistsPostOKResultItemResultUnsupported APIParsingBookExistsPostOKResultItemResult = "unsupported"
	APIParsingBookExistsPostOKResultItemResultError       APIParsingBookExistsPostOKResultItemResult = "error"
)

// AllValues returns all APIParsingBookExistsPostOKResultItemResult values.
func (APIParsingBookExistsPostOKResultItemResult) AllValues() []APIParsingBookExistsPostOKResultItemResult {
	return []APIParsingBookExistsPostOKResultItemResult{
		APIParsingBookExistsPostOKResultItemResultOk,
		APIParsingBookExistsPostOKResultItemResultUnsupported,
		APIParsingBookExistsPostOKResultItemResultError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIParsingBookExistsPostOKResultItemResult) MarshalText() ([]byte, error) {
	switch s {
	case APIParsingBookExistsPostOKResultItemResultOk:
		return []byte(s), nil
	case APIParsingBookExistsPostOKResultItemResultUnsupported:
		return []byte(s), nil
	case APIParsingBookExistsPostOKResultItemResultError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIParsingBookExistsPostOKResultItemResult) UnmarshalText(data []byte) error {
	switch APIParsingBookExistsPostOKResultItemResult(data) {
	case APIParsingBookExistsPostOKResultItemResultOk:
		*s = APIParsingBookExistsPostOKResultItemResultOk
		return nil
	case APIParsingBookExistsPostOKResultItemResultUnsupported:
		*s = APIParsingBookExistsPostOKResultItemResultUnsupported
		return nil
	case APIParsingBookExistsPostOKResultItemResultError:
		*s = APIParsingBookExistsPostOKResultItemResultError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type APIParsingBookExistsPostReq struct {
	// Ссылки на внешние системы.
	Urls []url.URL `json:"urls"`
}

// GetUrls returns the value of Urls.
func (s *APIParsingBookExistsPostReq) GetUrls() []url.URL {
	return s.Urls
}

// SetUrls sets the value of Urls.
func (s *APIParsingBookExistsPostReq) SetUrls(val []url.URL) {
	s.Urls = val
}

type APIParsingBookExistsPostUnauthorized ErrorResponse

func (*APIParsingBookExistsPostUnauthorized) aPIParsingBookExistsPostRes() {}

type APIParsingPageExistsPostBadRequest ErrorResponse

func (*APIParsingPageExistsPostBadRequest) aPIParsingPageExistsPostRes() {}

type APIParsingPageExistsPostForbidden ErrorResponse

func (*APIParsingPageExistsPostForbidden) aPIParsingPageExistsPostRes() {}

type APIParsingPageExistsPostInternalServerError ErrorResponse

func (*APIParsingPageExistsPostInternalServerError) aPIParsingPageExistsPostRes() {}

type APIParsingPageExistsPostOK struct {
	// Результат обработки.
	Result []APIParsingPageExistsPostOKResultItem `json:"result"`
}

// GetResult returns the value of Result.
func (s *APIParsingPageExistsPostOK) GetResult() []APIParsingPageExistsPostOKResultItem {
	return s.Result
}

// SetResult sets the value of Result.
func (s *APIParsingPageExistsPostOK) SetResult(val []APIParsingPageExistsPostOKResultItem) {
	s.Result = val
}

func (*APIParsingPageExistsPostOK) aPIParsingPageExistsPostRes() {}

type APIParsingPageExistsPostOKResultItem struct {
	// Ссылка на книгу во внешней системе.
	BookURL url.URL `json:"book_url"`
	// Ссылка на изображение во внешней системе.
	ImageURL url.URL `json:"image_url"`
	// Результат проверки.
	Result APIParsingPageExistsPostOKResultItemResult `json:"result"`
	// Данные об ошибке во время обработки.
	ErrorDetails OptString `json:"error_details"`
}

// GetBookURL returns the value of BookURL.
func (s *APIParsingPageExistsPostOKResultItem) GetBookURL() url.URL {
	return s.BookURL
}

// GetImageURL returns the value of ImageURL.
func (s *APIParsingPageExistsPostOKResultItem) GetImageURL() url.URL {
	return s.ImageURL
}

// GetResult returns the value of Result.
func (s *APIParsingPageExistsPostOKResultItem) GetResult() APIParsingPageExistsPostOKResultItemResult {
	return s.Result
}

// GetErrorDetails returns the value of ErrorDetails.
func (s *APIParsingPageExistsPostOKResultItem) GetErrorDetails() OptString {
	return s.ErrorDetails
}

// SetBookURL sets the value of BookURL.
func (s *APIParsingPageExistsPostOKResultItem) SetBookURL(val url.URL) {
	s.BookURL = val
}

// SetImageURL sets the value of ImageURL.
func (s *APIParsingPageExistsPostOKResultItem) SetImageURL(val url.URL) {
	s.ImageURL = val
}

// SetResult sets the value of Result.
func (s *APIParsingPageExistsPostOKResultItem) SetResult(val APIParsingPageExistsPostOKResultItemResult) {
	s.Result = val
}

// SetErrorDetails sets the value of ErrorDetails.
func (s *APIParsingPageExistsPostOKResultItem) SetErrorDetails(val OptString) {
	s.ErrorDetails = val
}

// Результат проверки.
type APIParsingPageExistsPostOKResultItemResult string

const (
	APIParsingPageExistsPostOKResultItemResultOk          APIParsingPageExistsPostOKResultItemResult = "ok"
	APIParsingPageExistsPostOKResultItemResultUnsupported APIParsingPageExistsPostOKResultItemResult = "unsupported"
	APIParsingPageExistsPostOKResultItemResultError       APIParsingPageExistsPostOKResultItemResult = "error"
)

// AllValues returns all APIParsingPageExistsPostOKResultItemResult values.
func (APIParsingPageExistsPostOKResultItemResult) AllValues() []APIParsingPageExistsPostOKResultItemResult {
	return []APIParsingPageExistsPostOKResultItemResult{
		APIParsingPageExistsPostOKResultItemResultOk,
		APIParsingPageExistsPostOKResultItemResultUnsupported,
		APIParsingPageExistsPostOKResultItemResultError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIParsingPageExistsPostOKResultItemResult) MarshalText() ([]byte, error) {
	switch s {
	case APIParsingPageExistsPostOKResultItemResultOk:
		return []byte(s), nil
	case APIParsingPageExistsPostOKResultItemResultUnsupported:
		return []byte(s), nil
	case APIParsingPageExistsPostOKResultItemResultError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIParsingPageExistsPostOKResultItemResult) UnmarshalText(data []byte) error {
	switch APIParsingPageExistsPostOKResultItemResult(data) {
	case APIParsingPageExistsPostOKResultItemResultOk:
		*s = APIParsingPageExistsPostOKResultItemResultOk
		return nil
	case APIParsingPageExistsPostOKResultItemResultUnsupported:
		*s = APIParsingPageExistsPostOKResultItemResultUnsupported
		return nil
	case APIParsingPageExistsPostOKResultItemResultError:
		*s = APIParsingPageExistsPostOKResultItemResultError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type APIParsingPageExistsPostReq struct {
	// Ссылки на внешние системы.
	Urls []APIParsingPageExistsPostReqUrlsItem `json:"urls"`
}

// GetUrls returns the value of Urls.
func (s *APIParsingPageExistsPostReq) GetUrls() []APIParsingPageExistsPostReqUrlsItem {
	return s.Urls
}

// SetUrls sets the value of Urls.
func (s *APIParsingPageExistsPostReq) SetUrls(val []APIParsingPageExistsPostReqUrlsItem) {
	s.Urls = val
}

type APIParsingPageExistsPostReqUrlsItem struct {
	// Ссылка на книгу во внешней системе.
	BookURL url.URL `json:"book_url"`
	// Ссылка на изображение во внешней системе.
	ImageURL url.URL `json:"image_url"`
}

// GetBookURL returns the value of BookURL.
func (s *APIParsingPageExistsPostReqUrlsItem) GetBookURL() url.URL {
	return s.BookURL
}

// GetImageURL returns the value of ImageURL.
func (s *APIParsingPageExistsPostReqUrlsItem) GetImageURL() url.URL {
	return s.ImageURL
}

// SetBookURL sets the value of BookURL.
func (s *APIParsingPageExistsPostReqUrlsItem) SetBookURL(val url.URL) {
	s.BookURL = val
}

// SetImageURL sets the value of ImageURL.
func (s *APIParsingPageExistsPostReqUrlsItem) SetImageURL(val url.URL) {
	s.ImageURL = val
}

type APIParsingPageExistsPostUnauthorized ErrorResponse

func (*APIParsingPageExistsPostUnauthorized) aPIParsingPageExistsPostRes() {}

type APISystemDeduplicateArchivePostBadRequest ErrorResponse

func (*APISystemDeduplicateArchivePostBadRequest) aPISystemDeduplicateArchivePostRes() {}

type APISystemDeduplicateArchivePostForbidden ErrorResponse

func (*APISystemDeduplicateArchivePostForbidden) aPISystemDeduplicateArchivePostRes() {}

type APISystemDeduplicateArchivePostInternalServerError ErrorResponse

func (*APISystemDeduplicateArchivePostInternalServerError) aPISystemDeduplicateArchivePostRes() {}

type APISystemDeduplicateArchivePostOKApplicationJSON []APISystemDeduplicateArchivePostOKItem

func (*APISystemDeduplicateArchivePostOKApplicationJSON) aPISystemDeduplicateArchivePostRes() {}

type APISystemDeduplicateArchivePostOKItem struct {
	// ID книги.
	BookID uuid.UUID `json:"book_id"`
	// Оригинальный адрес книги.
	BookOriginURL OptURI `json:"book_origin_url"`
	// Процент (0-1) вхождения архива в книгу.
	EntryPercentage float64 `json:"entry_percentage"`
	// Процент (0-1) вхождения книги в архив.
	ReverseEntryPercentage float64 `json:"reverse_entry_percentage"`
}

// GetBookID returns the value of BookID.
func (s *APISystemDeduplicateArchivePostOKItem) GetBookID() uuid.UUID {
	return s.BookID
}

// GetBookOriginURL returns the value of BookOriginURL.
func (s *APISystemDeduplicateArchivePostOKItem) GetBookOriginURL() OptURI {
	return s.BookOriginURL
}

// GetEntryPercentage returns the value of EntryPercentage.
func (s *APISystemDeduplicateArchivePostOKItem) GetEntryPercentage() float64 {
	return s.EntryPercentage
}

// GetReverseEntryPercentage returns the value of ReverseEntryPercentage.
func (s *APISystemDeduplicateArchivePostOKItem) GetReverseEntryPercentage() float64 {
	return s.ReverseEntryPercentage
}

// SetBookID sets the value of BookID.
func (s *APISystemDeduplicateArchivePostOKItem) SetBookID(val uuid.UUID) {
	s.BookID = val
}

// SetBookOriginURL sets the value of BookOriginURL.
func (s *APISystemDeduplicateArchivePostOKItem) SetBookOriginURL(val OptURI) {
	s.BookOriginURL = val
}

// SetEntryPercentage sets the value of EntryPercentage.
func (s *APISystemDeduplicateArchivePostOKItem) SetEntryPercentage(val float64) {
	s.EntryPercentage = val
}

// SetReverseEntryPercentage sets the value of ReverseEntryPercentage.
func (s *APISystemDeduplicateArchivePostOKItem) SetReverseEntryPercentage(val float64) {
	s.ReverseEntryPercentage = val
}

type APISystemDeduplicateArchivePostReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APISystemDeduplicateArchivePostReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type APISystemDeduplicateArchivePostUnauthorized ErrorResponse

func (*APISystemDeduplicateArchivePostUnauthorized) aPISystemDeduplicateArchivePostRes() {}

type APISystemHandlePostBadRequest ErrorResponse

func (*APISystemHandlePostBadRequest) aPISystemHandlePostRes() {}

type APISystemHandlePostForbidden ErrorResponse

func (*APISystemHandlePostForbidden) aPISystemHandlePostRes() {}

type APISystemHandlePostInternalServerError ErrorResponse

func (*APISystemHandlePostInternalServerError) aPISystemHandlePostRes() {}

type APISystemHandlePostOK struct {
	// Общее количество обработанных.
	TotalCount int `json:"total_count"`
	// Количество загруженных (успешно обработанных).
	LoadedCount int `json:"loaded_count"`
	// Количество дубликатов (пропущенных).
	DuplicateCount int `json:"duplicate_count"`
	// Количество неудачных обработок.
	ErrorCount int `json:"error_count"`
	// Не обработанные ссылки.
	NotHandled []url.URL `json:"not_handled"`
	// Подробности результата обработки.
	Details []APISystemHandlePostOKDetailsItem `json:"details"`
}

// GetTotalCount returns the value of TotalCount.
func (s *APISystemHandlePostOK) GetTotalCount() int {
	return s.TotalCount
}

// GetLoadedCount returns the value of LoadedCount.
func (s *APISystemHandlePostOK) GetLoadedCount() int {
	return s.LoadedCount
}

// GetDuplicateCount returns the value of DuplicateCount.
func (s *APISystemHandlePostOK) GetDuplicateCount() int {
	return s.DuplicateCount
}

// GetErrorCount returns the value of ErrorCount.
func (s *APISystemHandlePostOK) GetErrorCount() int {
	return s.ErrorCount
}

// GetNotHandled returns the value of NotHandled.
func (s *APISystemHandlePostOK) GetNotHandled() []url.URL {
	return s.NotHandled
}

// GetDetails returns the value of Details.
func (s *APISystemHandlePostOK) GetDetails() []APISystemHandlePostOKDetailsItem {
	return s.Details
}

// SetTotalCount sets the value of TotalCount.
func (s *APISystemHandlePostOK) SetTotalCount(val int) {
	s.TotalCount = val
}

// SetLoadedCount sets the value of LoadedCount.
func (s *APISystemHandlePostOK) SetLoadedCount(val int) {
	s.LoadedCount = val
}

// SetDuplicateCount sets the value of DuplicateCount.
func (s *APISystemHandlePostOK) SetDuplicateCount(val int) {
	s.DuplicateCount = val
}

// SetErrorCount sets the value of ErrorCount.
func (s *APISystemHandlePostOK) SetErrorCount(val int) {
	s.ErrorCount = val
}

// SetNotHandled sets the value of NotHandled.
func (s *APISystemHandlePostOK) SetNotHandled(val []url.URL) {
	s.NotHandled = val
}

// SetDetails sets the value of Details.
func (s *APISystemHandlePostOK) SetDetails(val []APISystemHandlePostOKDetailsItem) {
	s.Details = val
}

func (*APISystemHandlePostOK) aPISystemHandlePostRes() {}

type APISystemHandlePostOKDetailsItem struct {
	// Изначальная ссылка.
	URL url.URL `json:"url"`
	// Эта дубликат другой книги.
	IsDuplicate bool `json:"is_duplicate"`
	// ID книги в системе которую дублирует текущая.
	DuplicateID OptUUID `json:"duplicate_id"`
	// Книга успешно обработана и добавлена в систему.
	IsHandled bool `json:"is_handled"`
	// Описание ошибки которое произошло во время обработки.
	ErrorReason OptString `json:"error_reason"`
}

// GetURL returns the value of URL.
func (s *APISystemHandlePostOKDetailsItem) GetURL() url.URL {
	return s.URL
}

// GetIsDuplicate returns the value of IsDuplicate.
func (s *APISystemHandlePostOKDetailsItem) GetIsDuplicate() bool {
	return s.IsDuplicate
}

// GetDuplicateID returns the value of DuplicateID.
func (s *APISystemHandlePostOKDetailsItem) GetDuplicateID() OptUUID {
	return s.DuplicateID
}

// GetIsHandled returns the value of IsHandled.
func (s *APISystemHandlePostOKDetailsItem) GetIsHandled() bool {
	return s.IsHandled
}

// GetErrorReason returns the value of ErrorReason.
func (s *APISystemHandlePostOKDetailsItem) GetErrorReason() OptString {
	return s.ErrorReason
}

// SetURL sets the value of URL.
func (s *APISystemHandlePostOKDetailsItem) SetURL(val url.URL) {
	s.URL = val
}

// SetIsDuplicate sets the value of IsDuplicate.
func (s *APISystemHandlePostOKDetailsItem) SetIsDuplicate(val bool) {
	s.IsDuplicate = val
}

// SetDuplicateID sets the value of DuplicateID.
func (s *APISystemHandlePostOKDetailsItem) SetDuplicateID(val OptUUID) {
	s.DuplicateID = val
}

// SetIsHandled sets the value of IsHandled.
func (s *APISystemHandlePostOKDetailsItem) SetIsHandled(val bool) {
	s.IsHandled = val
}

// SetErrorReason sets the value of ErrorReason.
func (s *APISystemHandlePostOKDetailsItem) SetErrorReason(val OptString) {
	s.ErrorReason = val
}

type APISystemHandlePostReq struct {
	// Ссылки на внешние системы.
	Urls []url.URL `json:"urls"`
	// Режим обработки мульти ссылок (на тома книг).
	IsMulti OptBool `json:"is_multi"`
}

// GetUrls returns the value of Urls.
func (s *APISystemHandlePostReq) GetUrls() []url.URL {
	return s.Urls
}

// GetIsMulti returns the value of IsMulti.
func (s *APISystemHandlePostReq) GetIsMulti() OptBool {
	return s.IsMulti
}

// SetUrls sets the value of Urls.
func (s *APISystemHandlePostReq) SetUrls(val []url.URL) {
	s.Urls = val
}

// SetIsMulti sets the value of IsMulti.
func (s *APISystemHandlePostReq) SetIsMulti(val OptBool) {
	s.IsMulti = val
}

type APISystemHandlePostUnauthorized ErrorResponse

func (*APISystemHandlePostUnauthorized) aPISystemHandlePostRes() {}

type APISystemImportArchivePostBadRequest ErrorResponse

func (*APISystemImportArchivePostBadRequest) aPISystemImportArchivePostRes() {}

type APISystemImportArchivePostForbidden ErrorResponse

func (*APISystemImportArchivePostForbidden) aPISystemImportArchivePostRes() {}

type APISystemImportArchivePostInternalServerError ErrorResponse

func (*APISystemImportArchivePostInternalServerError) aPISystemImportArchivePostRes() {}

type APISystemImportArchivePostOK struct {
	// ID новой книги.
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APISystemImportArchivePostOK) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APISystemImportArchivePostOK) SetID(val uuid.UUID) {
	s.ID = val
}

func (*APISystemImportArchivePostOK) aPISystemImportArchivePostRes() {}

type APISystemImportArchivePostReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s APISystemImportArchivePostReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type APISystemImportArchivePostUnauthorized ErrorResponse

func (*APISystemImportArchivePostUnauthorized) aPISystemImportArchivePostRes() {}

type APISystemInfoGetForbidden ErrorResponse

func (*APISystemInfoGetForbidden) aPISystemInfoGetRes() {}

type APISystemInfoGetInternalServerError ErrorResponse

func (*APISystemInfoGetInternalServerError) aPISystemInfoGetRes() {}

type APISystemInfoGetUnauthorized ErrorResponse

func (*APISystemInfoGetUnauthorized) aPISystemInfoGetRes() {}

type APISystemRPCDeduplicateFilesPostBadRequest ErrorResponse

func (*APISystemRPCDeduplicateFilesPostBadRequest) aPISystemRPCDeduplicateFilesPostRes() {}

type APISystemRPCDeduplicateFilesPostForbidden ErrorResponse

func (*APISystemRPCDeduplicateFilesPostForbidden) aPISystemRPCDeduplicateFilesPostRes() {}

type APISystemRPCDeduplicateFilesPostInternalServerError ErrorResponse

func (*APISystemRPCDeduplicateFilesPostInternalServerError) aPISystemRPCDeduplicateFilesPostRes() {}

type APISystemRPCDeduplicateFilesPostOK struct {
	// Количество файлов дублей.
	Count int `json:"count"`
	// Размер файлов дублей.
	Size int64 `json:"size"`
	// Размер файлов дублей в человеко-читаемом формате.
	PrettySize string `json:"pretty_size"`
}

// GetCount returns the value of Count.
func (s *APISystemRPCDeduplicateFilesPostOK) GetCount() int {
	return s.Count
}

// GetSize returns the value of Size.
func (s *APISystemRPCDeduplicateFilesPostOK) GetSize() int64 {
	return s.Size
}

// GetPrettySize returns the value of PrettySize.
func (s *APISystemRPCDeduplicateFilesPostOK) GetPrettySize() string {
	return s.PrettySize
}

// SetCount sets the value of Count.
func (s *APISystemRPCDeduplicateFilesPostOK) SetCount(val int) {
	s.Count = val
}

// SetSize sets the value of Size.
func (s *APISystemRPCDeduplicateFilesPostOK) SetSize(val int64) {
	s.Size = val
}

// SetPrettySize sets the value of PrettySize.
func (s *APISystemRPCDeduplicateFilesPostOK) SetPrettySize(val string) {
	s.PrettySize = val
}

func (*APISystemRPCDeduplicateFilesPostOK) aPISystemRPCDeduplicateFilesPostRes() {}

type APISystemRPCDeduplicateFilesPostUnauthorized ErrorResponse

func (*APISystemRPCDeduplicateFilesPostUnauthorized) aPISystemRPCDeduplicateFilesPostRes() {}

type APISystemRPCRemoveDetachedFilesPostBadRequest ErrorResponse

func (*APISystemRPCRemoveDetachedFilesPostBadRequest) aPISystemRPCRemoveDetachedFilesPostRes() {}

type APISystemRPCRemoveDetachedFilesPostForbidden ErrorResponse

func (*APISystemRPCRemoveDetachedFilesPostForbidden) aPISystemRPCRemoveDetachedFilesPostRes() {}

type APISystemRPCRemoveDetachedFilesPostInternalServerError ErrorResponse

func (*APISystemRPCRemoveDetachedFilesPostInternalServerError) aPISystemRPCRemoveDetachedFilesPostRes() {
}

type APISystemRPCRemoveDetachedFilesPostOK struct {
	// Количество удаленных файлов.
	Count int `json:"count"`
	// Размер удаленных файлов.
	Size int64 `json:"size"`
	// Размер удаленных файлов в человеко-читаемом формате.
	PrettySize string `json:"pretty_size"`
}

// GetCount returns the value of Count.
func (s *APISystemRPCRemoveDetachedFilesPostOK) GetCount() int {
	return s.Count
}

// GetSize returns the value of Size.
func (s *APISystemRPCRemoveDetachedFilesPostOK) GetSize() int64 {
	return s.Size
}

// GetPrettySize returns the value of PrettySize.
func (s *APISystemRPCRemoveDetachedFilesPostOK) GetPrettySize() string {
	return s.PrettySize
}

// SetCount sets the value of Count.
func (s *APISystemRPCRemoveDetachedFilesPostOK) SetCount(val int) {
	s.Count = val
}

// SetSize sets the value of Size.
func (s *APISystemRPCRemoveDetachedFilesPostOK) SetSize(val int64) {
	s.Size = val
}

// SetPrettySize sets the value of PrettySize.
func (s *APISystemRPCRemoveDetachedFilesPostOK) SetPrettySize(val string) {
	s.PrettySize = val
}

func (*APISystemRPCRemoveDetachedFilesPostOK) aPISystemRPCRemoveDetachedFilesPostRes() {}

type APISystemRPCRemoveDetachedFilesPostUnauthorized ErrorResponse

func (*APISystemRPCRemoveDetachedFilesPostUnauthorized) aPISystemRPCRemoveDetachedFilesPostRes() {}

type APISystemRPCRemoveMismatchFilesPostBadRequest ErrorResponse

func (*APISystemRPCRemoveMismatchFilesPostBadRequest) aPISystemRPCRemoveMismatchFilesPostRes() {}

type APISystemRPCRemoveMismatchFilesPostForbidden ErrorResponse

func (*APISystemRPCRemoveMismatchFilesPostForbidden) aPISystemRPCRemoveMismatchFilesPostRes() {}

type APISystemRPCRemoveMismatchFilesPostInternalServerError ErrorResponse

func (*APISystemRPCRemoveMismatchFilesPostInternalServerError) aPISystemRPCRemoveMismatchFilesPostRes() {
}

type APISystemRPCRemoveMismatchFilesPostOK struct {
	// Количество удаленных файлов из БД.
	RemoveFromDb int `json:"remove_from_db"`
	// Количество удаленных файлов из файловой системы.
	RemoveFromFs int `json:"remove_from_fs"`
}

// GetRemoveFromDb returns the value of RemoveFromDb.
func (s *APISystemRPCRemoveMismatchFilesPostOK) GetRemoveFromDb() int {
	return s.RemoveFromDb
}

// GetRemoveFromFs returns the value of RemoveFromFs.
func (s *APISystemRPCRemoveMismatchFilesPostOK) GetRemoveFromFs() int {
	return s.RemoveFromFs
}

// SetRemoveFromDb sets the value of RemoveFromDb.
func (s *APISystemRPCRemoveMismatchFilesPostOK) SetRemoveFromDb(val int) {
	s.RemoveFromDb = val
}

// SetRemoveFromFs sets the value of RemoveFromFs.
func (s *APISystemRPCRemoveMismatchFilesPostOK) SetRemoveFromFs(val int) {
	s.RemoveFromFs = val
}

func (*APISystemRPCRemoveMismatchFilesPostOK) aPISystemRPCRemoveMismatchFilesPostRes() {}

type APISystemRPCRemoveMismatchFilesPostUnauthorized ErrorResponse

func (*APISystemRPCRemoveMismatchFilesPostUnauthorized) aPISystemRPCRemoveMismatchFilesPostRes() {}

type APISystemWorkerConfigPostBadRequest ErrorResponse

func (*APISystemWorkerConfigPostBadRequest) aPISystemWorkerConfigPostRes() {}

type APISystemWorkerConfigPostForbidden ErrorResponse

func (*APISystemWorkerConfigPostForbidden) aPISystemWorkerConfigPostRes() {}

type APISystemWorkerConfigPostInternalServerError ErrorResponse

func (*APISystemWorkerConfigPostInternalServerError) aPISystemWorkerConfigPostRes() {}

// APISystemWorkerConfigPostNoContent is response for APISystemWorkerConfigPost operation.
type APISystemWorkerConfigPostNoContent struct{}

func (*APISystemWorkerConfigPostNoContent) aPISystemWorkerConfigPostRes() {}

type APISystemWorkerConfigPostReq struct {
	// Количество раннеров.
	RunnersCount []APISystemWorkerConfigPostReqRunnersCountItem `json:"runners_count"`
}

// GetRunnersCount returns the value of RunnersCount.
func (s *APISystemWorkerConfigPostReq) GetRunnersCount() []APISystemWorkerConfigPostReqRunnersCountItem {
	return s.RunnersCount
}

// SetRunnersCount sets the value of RunnersCount.
func (s *APISystemWorkerConfigPostReq) SetRunnersCount(val []APISystemWorkerConfigPostReqRunnersCountItem) {
	s.RunnersCount = val
}

type APISystemWorkerConfigPostReqRunnersCountItem struct {
	// Название (код) раннера.
	Name string `json:"name"`
	// Новое количество раннеров.
	Count int `json:"count"`
}

// GetName returns the value of Name.
func (s *APISystemWorkerConfigPostReqRunnersCountItem) GetName() string {
	return s.Name
}

// GetCount returns the value of Count.
func (s *APISystemWorkerConfigPostReqRunnersCountItem) GetCount() int {
	return s.Count
}

// SetName sets the value of Name.
func (s *APISystemWorkerConfigPostReqRunnersCountItem) SetName(val string) {
	s.Name = val
}

// SetCount sets the value of Count.
func (s *APISystemWorkerConfigPostReqRunnersCountItem) SetCount(val int) {
	s.Count = val
}

type APISystemWorkerConfigPostUnauthorized ErrorResponse

func (*APISystemWorkerConfigPostUnauthorized) aPISystemWorkerConfigPostRes() {}

type APIUserLoginPostBadRequest ErrorResponse

func (*APIUserLoginPostBadRequest) aPIUserLoginPostRes() {}

type APIUserLoginPostInternalServerError ErrorResponse

func (*APIUserLoginPostInternalServerError) aPIUserLoginPostRes() {}

// APIUserLoginPostNoContent is response for APIUserLoginPost operation.
type APIUserLoginPostNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *APIUserLoginPostNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *APIUserLoginPostNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*APIUserLoginPostNoContent) aPIUserLoginPostRes() {}

type APIUserLoginPostReq struct {
	// Токен пользователя.
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *APIUserLoginPostReq) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *APIUserLoginPostReq) SetToken(val string) {
	s.Token = val
}

// Данные книги.
// Ref: #/components/schemas/BookDetails
type BookDetails struct {
	// ID книги.
	ID uuid.UUID `json:"id"`
	// Время создания книги в системе.
	Created time.Time `json:"created"`
	// Ссылка для предпросмотра изображения книги.
	PreviewURL OptURI `json:"preview_url"`
	// Было ли обработано название книги.
	ParsedName bool `json:"parsed_name"`
	// Название книги.
	Name string `json:"name"`
	// Были ли обработаны страницы.
	ParsedPage bool `json:"parsed_page"`
	// Количество страниц.
	PageCount int `json:"page_count"`
	// Процент загруженных страниц.
	PageLoadedPercent float64 `json:"page_loaded_percent"`
	// Данные атрибутов книги.
	Attributes []BookDetailsAttributesItem `json:"attributes"`
	// Данные страниц книги.
	Pages []BookDetailsPagesItem `json:"pages"`
}

// GetID returns the value of ID.
func (s *BookDetails) GetID() uuid.UUID {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *BookDetails) GetCreated() time.Time {
	return s.Created
}

// GetPreviewURL returns the value of PreviewURL.
func (s *BookDetails) GetPreviewURL() OptURI {
	return s.PreviewURL
}

// GetParsedName returns the value of ParsedName.
func (s *BookDetails) GetParsedName() bool {
	return s.ParsedName
}

// GetName returns the value of Name.
func (s *BookDetails) GetName() string {
	return s.Name
}

// GetParsedPage returns the value of ParsedPage.
func (s *BookDetails) GetParsedPage() bool {
	return s.ParsedPage
}

// GetPageCount returns the value of PageCount.
func (s *BookDetails) GetPageCount() int {
	return s.PageCount
}

// GetPageLoadedPercent returns the value of PageLoadedPercent.
func (s *BookDetails) GetPageLoadedPercent() float64 {
	return s.PageLoadedPercent
}

// GetAttributes returns the value of Attributes.
func (s *BookDetails) GetAttributes() []BookDetailsAttributesItem {
	return s.Attributes
}

// GetPages returns the value of Pages.
func (s *BookDetails) GetPages() []BookDetailsPagesItem {
	return s.Pages
}

// SetID sets the value of ID.
func (s *BookDetails) SetID(val uuid.UUID) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *BookDetails) SetCreated(val time.Time) {
	s.Created = val
}

// SetPreviewURL sets the value of PreviewURL.
func (s *BookDetails) SetPreviewURL(val OptURI) {
	s.PreviewURL = val
}

// SetParsedName sets the value of ParsedName.
func (s *BookDetails) SetParsedName(val bool) {
	s.ParsedName = val
}

// SetName sets the value of Name.
func (s *BookDetails) SetName(val string) {
	s.Name = val
}

// SetParsedPage sets the value of ParsedPage.
func (s *BookDetails) SetParsedPage(val bool) {
	s.ParsedPage = val
}

// SetPageCount sets the value of PageCount.
func (s *BookDetails) SetPageCount(val int) {
	s.PageCount = val
}

// SetPageLoadedPercent sets the value of PageLoadedPercent.
func (s *BookDetails) SetPageLoadedPercent(val float64) {
	s.PageLoadedPercent = val
}

// SetAttributes sets the value of Attributes.
func (s *BookDetails) SetAttributes(val []BookDetailsAttributesItem) {
	s.Attributes = val
}

// SetPages sets the value of Pages.
func (s *BookDetails) SetPages(val []BookDetailsPagesItem) {
	s.Pages = val
}

func (*BookDetails) aPIBookDetailsPostRes() {}

type BookDetailsAttributesItem struct {
	// Название атрибута.
	Name string `json:"name"`
	// Значения атрибута.
	Values []string `json:"values"`
}

// GetName returns the value of Name.
func (s *BookDetailsAttributesItem) GetName() string {
	return s.Name
}

// GetValues returns the value of Values.
func (s *BookDetailsAttributesItem) GetValues() []string {
	return s.Values
}

// SetName sets the value of Name.
func (s *BookDetailsAttributesItem) SetName(val string) {
	s.Name = val
}

// SetValues sets the value of Values.
func (s *BookDetailsAttributesItem) SetValues(val []string) {
	s.Values = val
}

type BookDetailsPagesItem struct {
	// Номер страницы в книге.
	PageNumber int `json:"page_number"`
	// Ссылка на изображение для предпросмотра.
	PreviewURL OptURI `json:"preview_url"`
}

// GetPageNumber returns the value of PageNumber.
func (s *BookDetailsPagesItem) GetPageNumber() int {
	return s.PageNumber
}

// GetPreviewURL returns the value of PreviewURL.
func (s *BookDetailsPagesItem) GetPreviewURL() OptURI {
	return s.PreviewURL
}

// SetPageNumber sets the value of PageNumber.
func (s *BookDetailsPagesItem) SetPageNumber(val int) {
	s.PageNumber = val
}

// SetPreviewURL sets the value of PreviewURL.
func (s *BookDetailsPagesItem) SetPreviewURL(val OptURI) {
	s.PreviewURL = val
}

// Данные книги.
// Ref: #/components/schemas/BookRaw
type BookRaw struct {
	// ID книги.
	ID uuid.UUID `json:"id"`
	// Время создания книги в системе.
	CreateAt time.Time `json:"create_at"`
	// Оригинальная ссылка на книгу.
	OriginURL OptURI `json:"origin_url"`
	// Название книги.
	Name string `json:"name"`
	// Количество страниц.
	PageCount int `json:"page_count"`
	// Данные атрибутов книги.
	Attributes []BookRawAttributesItem `json:"attributes"`
	// Данные страниц книги.
	Pages []BookRawPagesItem `json:"pages"`
	// Данные атрибутов книги.
	Labels []BookRawLabelsItem `json:"labels"`
}

// GetID returns the value of ID.
func (s *BookRaw) GetID() uuid.UUID {
	return s.ID
}

// GetCreateAt returns the value of CreateAt.
func (s *BookRaw) GetCreateAt() time.Time {
	return s.CreateAt
}

// GetOriginURL returns the value of OriginURL.
func (s *BookRaw) GetOriginURL() OptURI {
	return s.OriginURL
}

// GetName returns the value of Name.
func (s *BookRaw) GetName() string {
	return s.Name
}

// GetPageCount returns the value of PageCount.
func (s *BookRaw) GetPageCount() int {
	return s.PageCount
}

// GetAttributes returns the value of Attributes.
func (s *BookRaw) GetAttributes() []BookRawAttributesItem {
	return s.Attributes
}

// GetPages returns the value of Pages.
func (s *BookRaw) GetPages() []BookRawPagesItem {
	return s.Pages
}

// GetLabels returns the value of Labels.
func (s *BookRaw) GetLabels() []BookRawLabelsItem {
	return s.Labels
}

// SetID sets the value of ID.
func (s *BookRaw) SetID(val uuid.UUID) {
	s.ID = val
}

// SetCreateAt sets the value of CreateAt.
func (s *BookRaw) SetCreateAt(val time.Time) {
	s.CreateAt = val
}

// SetOriginURL sets the value of OriginURL.
func (s *BookRaw) SetOriginURL(val OptURI) {
	s.OriginURL = val
}

// SetName sets the value of Name.
func (s *BookRaw) SetName(val string) {
	s.Name = val
}

// SetPageCount sets the value of PageCount.
func (s *BookRaw) SetPageCount(val int) {
	s.PageCount = val
}

// SetAttributes sets the value of Attributes.
func (s *BookRaw) SetAttributes(val []BookRawAttributesItem) {
	s.Attributes = val
}

// SetPages sets the value of Pages.
func (s *BookRaw) SetPages(val []BookRawPagesItem) {
	s.Pages = val
}

// SetLabels sets the value of Labels.
func (s *BookRaw) SetLabels(val []BookRawLabelsItem) {
	s.Labels = val
}

func (*BookRaw) aPIBookRawPostRes() {}

type BookRawAttributesItem struct {
	// Код атрибута.
	Code string `json:"code"`
	// Значения атрибута.
	Values []string `json:"values"`
}

// GetCode returns the value of Code.
func (s *BookRawAttributesItem) GetCode() string {
	return s.Code
}

// GetValues returns the value of Values.
func (s *BookRawAttributesItem) GetValues() []string {
	return s.Values
}

// SetCode sets the value of Code.
func (s *BookRawAttributesItem) SetCode(val string) {
	s.Code = val
}

// SetValues sets the value of Values.
func (s *BookRawAttributesItem) SetValues(val []string) {
	s.Values = val
}

// Метка в системе.
type BookRawLabelsItem struct {
	// Номер страницы к которой привязана метка (0 если
	// привязана к книге).
	PageNumber int `json:"page_number"`
	// Код атрибута.
	Name string `json:"name"`
	// Значение.
	Value string `json:"value"`
	// Время создания отметки в системе.
	CreateAt time.Time `json:"create_at"`
}

// GetPageNumber returns the value of PageNumber.
func (s *BookRawLabelsItem) GetPageNumber() int {
	return s.PageNumber
}

// GetName returns the value of Name.
func (s *BookRawLabelsItem) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *BookRawLabelsItem) GetValue() string {
	return s.Value
}

// GetCreateAt returns the value of CreateAt.
func (s *BookRawLabelsItem) GetCreateAt() time.Time {
	return s.CreateAt
}

// SetPageNumber sets the value of PageNumber.
func (s *BookRawLabelsItem) SetPageNumber(val int) {
	s.PageNumber = val
}

// SetName sets the value of Name.
func (s *BookRawLabelsItem) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *BookRawLabelsItem) SetValue(val string) {
	s.Value = val
}

// SetCreateAt sets the value of CreateAt.
func (s *BookRawLabelsItem) SetCreateAt(val time.Time) {
	s.CreateAt = val
}

type BookRawPagesItem struct {
	// Номер страницы в книге.
	PageNumber int `json:"page_number"`
	// Ссылка на оригинальное изображение.
	OriginURL OptURI `json:"origin_url"`
	// Расширение файла.
	Ext string `json:"ext"`
	// Время создания страницы в системе.
	CreateAt time.Time `json:"create_at"`
	// Загружено ли тело страницы.
	Downloaded bool `json:"downloaded"`
	// Время загрузки тела страницы.
	LoadAt OptDateTime `json:"load_at"`
}

// GetPageNumber returns the value of PageNumber.
func (s *BookRawPagesItem) GetPageNumber() int {
	return s.PageNumber
}

// GetOriginURL returns the value of OriginURL.
func (s *BookRawPagesItem) GetOriginURL() OptURI {
	return s.OriginURL
}

// GetExt returns the value of Ext.
func (s *BookRawPagesItem) GetExt() string {
	return s.Ext
}

// GetCreateAt returns the value of CreateAt.
func (s *BookRawPagesItem) GetCreateAt() time.Time {
	return s.CreateAt
}

// GetDownloaded returns the value of Downloaded.
func (s *BookRawPagesItem) GetDownloaded() bool {
	return s.Downloaded
}

// GetLoadAt returns the value of LoadAt.
func (s *BookRawPagesItem) GetLoadAt() OptDateTime {
	return s.LoadAt
}

// SetPageNumber sets the value of PageNumber.
func (s *BookRawPagesItem) SetPageNumber(val int) {
	s.PageNumber = val
}

// SetOriginURL sets the value of OriginURL.
func (s *BookRawPagesItem) SetOriginURL(val OptURI) {
	s.OriginURL = val
}

// SetExt sets the value of Ext.
func (s *BookRawPagesItem) SetExt(val string) {
	s.Ext = val
}

// SetCreateAt sets the value of CreateAt.
func (s *BookRawPagesItem) SetCreateAt(val time.Time) {
	s.CreateAt = val
}

// SetDownloaded sets the value of Downloaded.
func (s *BookRawPagesItem) SetDownloaded(val bool) {
	s.Downloaded = val
}

// SetLoadAt sets the value of LoadAt.
func (s *BookRawPagesItem) SetLoadAt(val OptDateTime) {
	s.LoadAt = val
}

// Данные книги в упрощенном формате.
// Ref: #/components/schemas/BookShortInfo
type BookShortInfo struct {
	// ID книги.
	ID uuid.UUID `json:"id"`
	// Время создания книги в системе.
	Created time.Time `json:"created"`
	// Ссылка для предпросмотра изображения книги.
	PreviewURL OptURI `json:"preview_url"`
	// Было ли обработано название книги.
	ParsedName bool `json:"parsed_name"`
	// Название книги.
	Name string `json:"name"`
	// Были ли обработаны страницы.
	ParsedPage bool `json:"parsed_page"`
	// Количество страниц.
	PageCount int `json:"page_count"`
	// Процент загруженных страниц.
	PageLoadedPercent float64 `json:"page_loaded_percent"`
	// Список тегов (одноименный атрибут) книги.
	Tags []string `json:"tags"`
	// Есть теги которые не были включены в список.
	HasMoreTags bool `json:"has_more_tags"`
}

// GetID returns the value of ID.
func (s *BookShortInfo) GetID() uuid.UUID {
	return s.ID
}

// GetCreated returns the value of Created.
func (s *BookShortInfo) GetCreated() time.Time {
	return s.Created
}

// GetPreviewURL returns the value of PreviewURL.
func (s *BookShortInfo) GetPreviewURL() OptURI {
	return s.PreviewURL
}

// GetParsedName returns the value of ParsedName.
func (s *BookShortInfo) GetParsedName() bool {
	return s.ParsedName
}

// GetName returns the value of Name.
func (s *BookShortInfo) GetName() string {
	return s.Name
}

// GetParsedPage returns the value of ParsedPage.
func (s *BookShortInfo) GetParsedPage() bool {
	return s.ParsedPage
}

// GetPageCount returns the value of PageCount.
func (s *BookShortInfo) GetPageCount() int {
	return s.PageCount
}

// GetPageLoadedPercent returns the value of PageLoadedPercent.
func (s *BookShortInfo) GetPageLoadedPercent() float64 {
	return s.PageLoadedPercent
}

// GetTags returns the value of Tags.
func (s *BookShortInfo) GetTags() []string {
	return s.Tags
}

// GetHasMoreTags returns the value of HasMoreTags.
func (s *BookShortInfo) GetHasMoreTags() bool {
	return s.HasMoreTags
}

// SetID sets the value of ID.
func (s *BookShortInfo) SetID(val uuid.UUID) {
	s.ID = val
}

// SetCreated sets the value of Created.
func (s *BookShortInfo) SetCreated(val time.Time) {
	s.Created = val
}

// SetPreviewURL sets the value of PreviewURL.
func (s *BookShortInfo) SetPreviewURL(val OptURI) {
	s.PreviewURL = val
}

// SetParsedName sets the value of ParsedName.
func (s *BookShortInfo) SetParsedName(val bool) {
	s.ParsedName = val
}

// SetName sets the value of Name.
func (s *BookShortInfo) SetName(val string) {
	s.Name = val
}

// SetParsedPage sets the value of ParsedPage.
func (s *BookShortInfo) SetParsedPage(val bool) {
	s.ParsedPage = val
}

// SetPageCount sets the value of PageCount.
func (s *BookShortInfo) SetPageCount(val int) {
	s.PageCount = val
}

// SetPageLoadedPercent sets the value of PageLoadedPercent.
func (s *BookShortInfo) SetPageLoadedPercent(val float64) {
	s.PageLoadedPercent = val
}

// SetTags sets the value of Tags.
func (s *BookShortInfo) SetTags(val []string) {
	s.Tags = val
}

// SetHasMoreTags sets the value of HasMoreTags.
func (s *BookShortInfo) SetHasMoreTags(val bool) {
	s.HasMoreTags = val
}

type Cookies struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *Cookies) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *Cookies) SetAPIKey(val string) {
	s.APIKey = val
}

// Данные ошибки.
// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Внутренний код ошибки.
	InnerCode string `json:"inner_code"`
	// Детальные данные ошибки.
	Details OptString `json:"details"`
}

// GetInnerCode returns the value of InnerCode.
func (s *ErrorResponse) GetInnerCode() string {
	return s.InnerCode
}

// GetDetails returns the value of Details.
func (s *ErrorResponse) GetDetails() OptString {
	return s.Details
}

// SetInnerCode sets the value of InnerCode.
func (s *ErrorResponse) SetInnerCode(val string) {
	s.InnerCode = val
}

// SetDetails sets the value of Details.
func (s *ErrorResponse) SetDetails(val OptString) {
	s.Details = val
}

type HeaderAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *HeaderAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *HeaderAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// NewOptAPIAgentListPostOKItemStatus returns new OptAPIAgentListPostOKItemStatus with value set to v.
func NewOptAPIAgentListPostOKItemStatus(v APIAgentListPostOKItemStatus) OptAPIAgentListPostOKItemStatus {
	return OptAPIAgentListPostOKItemStatus{
		Value: v,
		Set:   true,
	}
}

// OptAPIAgentListPostOKItemStatus is optional APIAgentListPostOKItemStatus.
type OptAPIAgentListPostOKItemStatus struct {
	Value APIAgentListPostOKItemStatus
	Set   bool
}

// IsSet returns true if OptAPIAgentListPostOKItemStatus was set.
func (o OptAPIAgentListPostOKItemStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIAgentListPostOKItemStatus) Reset() {
	var v APIAgentListPostOKItemStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIAgentListPostOKItemStatus) SetTo(v APIAgentListPostOKItemStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIAgentListPostOKItemStatus) Get() (v APIAgentListPostOKItemStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIAgentListPostOKItemStatus) Or(d APIAgentListPostOKItemStatus) APIAgentListPostOKItemStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIBookListPostReqDeleteStatus returns new OptAPIBookListPostReqDeleteStatus with value set to v.
func NewOptAPIBookListPostReqDeleteStatus(v APIBookListPostReqDeleteStatus) OptAPIBookListPostReqDeleteStatus {
	return OptAPIBookListPostReqDeleteStatus{
		Value: v,
		Set:   true,
	}
}

// OptAPIBookListPostReqDeleteStatus is optional APIBookListPostReqDeleteStatus.
type OptAPIBookListPostReqDeleteStatus struct {
	Value APIBookListPostReqDeleteStatus
	Set   bool
}

// IsSet returns true if OptAPIBookListPostReqDeleteStatus was set.
func (o OptAPIBookListPostReqDeleteStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIBookListPostReqDeleteStatus) Reset() {
	var v APIBookListPostReqDeleteStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIBookListPostReqDeleteStatus) SetTo(v APIBookListPostReqDeleteStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIBookListPostReqDeleteStatus) Get() (v APIBookListPostReqDeleteStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIBookListPostReqDeleteStatus) Or(d APIBookListPostReqDeleteStatus) APIBookListPostReqDeleteStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIBookListPostReqFilter returns new OptAPIBookListPostReqFilter with value set to v.
func NewOptAPIBookListPostReqFilter(v APIBookListPostReqFilter) OptAPIBookListPostReqFilter {
	return OptAPIBookListPostReqFilter{
		Value: v,
		Set:   true,
	}
}

// OptAPIBookListPostReqFilter is optional APIBookListPostReqFilter.
type OptAPIBookListPostReqFilter struct {
	Value APIBookListPostReqFilter
	Set   bool
}

// IsSet returns true if OptAPIBookListPostReqFilter was set.
func (o OptAPIBookListPostReqFilter) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIBookListPostReqFilter) Reset() {
	var v APIBookListPostReqFilter
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIBookListPostReqFilter) SetTo(v APIBookListPostReqFilter) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIBookListPostReqFilter) Get() (v APIBookListPostReqFilter, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIBookListPostReqFilter) Or(d APIBookListPostReqFilter) APIBookListPostReqFilter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIBookListPostReqVerifyStatus returns new OptAPIBookListPostReqVerifyStatus with value set to v.
func NewOptAPIBookListPostReqVerifyStatus(v APIBookListPostReqVerifyStatus) OptAPIBookListPostReqVerifyStatus {
	return OptAPIBookListPostReqVerifyStatus{
		Value: v,
		Set:   true,
	}
}

// OptAPIBookListPostReqVerifyStatus is optional APIBookListPostReqVerifyStatus.
type OptAPIBookListPostReqVerifyStatus struct {
	Value APIBookListPostReqVerifyStatus
	Set   bool
}

// IsSet returns true if OptAPIBookListPostReqVerifyStatus was set.
func (o OptAPIBookListPostReqVerifyStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIBookListPostReqVerifyStatus) Reset() {
	var v APIBookListPostReqVerifyStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIBookListPostReqVerifyStatus) SetTo(v APIBookListPostReqVerifyStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIBookListPostReqVerifyStatus) Get() (v APIBookListPostReqVerifyStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIBookListPostReqVerifyStatus) Or(d APIBookListPostReqVerifyStatus) APIBookListPostReqVerifyStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSystemInfoMonitor returns new OptSystemInfoMonitor with value set to v.
func NewOptSystemInfoMonitor(v SystemInfoMonitor) OptSystemInfoMonitor {
	return OptSystemInfoMonitor{
		Value: v,
		Set:   true,
	}
}

// OptSystemInfoMonitor is optional SystemInfoMonitor.
type OptSystemInfoMonitor struct {
	Value SystemInfoMonitor
	Set   bool
}

// IsSet returns true if OptSystemInfoMonitor was set.
func (o OptSystemInfoMonitor) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSystemInfoMonitor) Reset() {
	var v SystemInfoMonitor
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSystemInfoMonitor) SetTo(v SystemInfoMonitor) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSystemInfoMonitor) Get() (v SystemInfoMonitor, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSystemInfoMonitor) Or(d SystemInfoMonitor) SystemInfoMonitor {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Информация о системе.
// Ref: #/components/schemas/SystemInfo
type SystemInfo struct {
	// Количество книг.
	Count int `json:"count"`
	// Количество не обработанных книг.
	NotLoadCount int `json:"not_load_count"`
	// Количество страниц.
	PageCount int `json:"page_count"`
	// Количество не загруженных страниц.
	NotLoadPageCount int `json:"not_load_page_count"`
	// Количество страниц без тела (файла).
	PageWithoutBodyCount int `json:"page_without_body_count"`
	// Объем загруженных изображений в байтах.
	PagesSize int64 `json:"pages_size"`
	// Объем загруженных изображений в человеко-читаемом
	// формате.
	PagesSizeFormatted string `json:"pages_size_formatted"`
	// Объем файлов в байтах.
	FilesSize int64 `json:"files_size"`
	// Объем файлов в человеко-читаемом формате.
	FilesSizeFormatted string `json:"files_size_formatted"`
	// Данные системы мониторинга.
	Monitor OptSystemInfoMonitor `json:"monitor"`
}

// GetCount returns the value of Count.
func (s *SystemInfo) GetCount() int {
	return s.Count
}

// GetNotLoadCount returns the value of NotLoadCount.
func (s *SystemInfo) GetNotLoadCount() int {
	return s.NotLoadCount
}

// GetPageCount returns the value of PageCount.
func (s *SystemInfo) GetPageCount() int {
	return s.PageCount
}

// GetNotLoadPageCount returns the value of NotLoadPageCount.
func (s *SystemInfo) GetNotLoadPageCount() int {
	return s.NotLoadPageCount
}

// GetPageWithoutBodyCount returns the value of PageWithoutBodyCount.
func (s *SystemInfo) GetPageWithoutBodyCount() int {
	return s.PageWithoutBodyCount
}

// GetPagesSize returns the value of PagesSize.
func (s *SystemInfo) GetPagesSize() int64 {
	return s.PagesSize
}

// GetPagesSizeFormatted returns the value of PagesSizeFormatted.
func (s *SystemInfo) GetPagesSizeFormatted() string {
	return s.PagesSizeFormatted
}

// GetFilesSize returns the value of FilesSize.
func (s *SystemInfo) GetFilesSize() int64 {
	return s.FilesSize
}

// GetFilesSizeFormatted returns the value of FilesSizeFormatted.
func (s *SystemInfo) GetFilesSizeFormatted() string {
	return s.FilesSizeFormatted
}

// GetMonitor returns the value of Monitor.
func (s *SystemInfo) GetMonitor() OptSystemInfoMonitor {
	return s.Monitor
}

// SetCount sets the value of Count.
func (s *SystemInfo) SetCount(val int) {
	s.Count = val
}

// SetNotLoadCount sets the value of NotLoadCount.
func (s *SystemInfo) SetNotLoadCount(val int) {
	s.NotLoadCount = val
}

// SetPageCount sets the value of PageCount.
func (s *SystemInfo) SetPageCount(val int) {
	s.PageCount = val
}

// SetNotLoadPageCount sets the value of NotLoadPageCount.
func (s *SystemInfo) SetNotLoadPageCount(val int) {
	s.NotLoadPageCount = val
}

// SetPageWithoutBodyCount sets the value of PageWithoutBodyCount.
func (s *SystemInfo) SetPageWithoutBodyCount(val int) {
	s.PageWithoutBodyCount = val
}

// SetPagesSize sets the value of PagesSize.
func (s *SystemInfo) SetPagesSize(val int64) {
	s.PagesSize = val
}

// SetPagesSizeFormatted sets the value of PagesSizeFormatted.
func (s *SystemInfo) SetPagesSizeFormatted(val string) {
	s.PagesSizeFormatted = val
}

// SetFilesSize sets the value of FilesSize.
func (s *SystemInfo) SetFilesSize(val int64) {
	s.FilesSize = val
}

// SetFilesSizeFormatted sets the value of FilesSizeFormatted.
func (s *SystemInfo) SetFilesSizeFormatted(val string) {
	s.FilesSizeFormatted = val
}

// SetMonitor sets the value of Monitor.
func (s *SystemInfo) SetMonitor(val OptSystemInfoMonitor) {
	s.Monitor = val
}

func (*SystemInfo) aPISystemInfoGetRes() {}

// Данные системы мониторинга.
type SystemInfoMonitor struct {
	// Данные об обработчиках.
	Workers []SystemInfoMonitorWorkersItem `json:"workers"`
}

// GetWorkers returns the value of Workers.
func (s *SystemInfoMonitor) GetWorkers() []SystemInfoMonitorWorkersItem {
	return s.Workers
}

// SetWorkers sets the value of Workers.
func (s *SystemInfoMonitor) SetWorkers(val []SystemInfoMonitorWorkersItem) {
	s.Workers = val
}

type SystemInfoMonitorWorkersItem struct {
	// Название обработчика.
	Name string `json:"name"`
	// В очереди на обработку.
	InQueue int `json:"in_queue"`
	// В обработке.
	InWork int `json:"in_work"`
	// Количество экземпляров обработчика (потоков).
	Runners int `json:"runners"`
}

// GetName returns the value of Name.
func (s *SystemInfoMonitorWorkersItem) GetName() string {
	return s.Name
}

// GetInQueue returns the value of InQueue.
func (s *SystemInfoMonitorWorkersItem) GetInQueue() int {
	return s.InQueue
}

// GetInWork returns the value of InWork.
func (s *SystemInfoMonitorWorkersItem) GetInWork() int {
	return s.InWork
}

// GetRunners returns the value of Runners.
func (s *SystemInfoMonitorWorkersItem) GetRunners() int {
	return s.Runners
}

// SetName sets the value of Name.
func (s *SystemInfoMonitorWorkersItem) SetName(val string) {
	s.Name = val
}

// SetInQueue sets the value of InQueue.
func (s *SystemInfoMonitorWorkersItem) SetInQueue(val int) {
	s.InQueue = val
}

// SetInWork sets the value of InWork.
func (s *SystemInfoMonitorWorkersItem) SetInWork(val int) {
	s.InWork = val
}

// SetRunners sets the value of Runners.
func (s *SystemInfoMonitorWorkersItem) SetRunners(val int) {
	s.Runners = val
}
